# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- master
- Dev1
- mahesh 

uri:https://aryakrishna247@dev.azure.com/aryakrishna247/Agiletest/_git/PipelinePipeline-Dev1.yml
uri:https://aryakrishna247@dev.azure.com/aryakrishna247/Agiletest/_git/Pipeline/Pipeline-Master.yml
uri:https://aryakrishna247@dev.azure.com/aryakrishna247/Agiletest/_git/Pipeline/Pipeline-mahesh.yml

pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- stages 
  
  - Dev1
  - master
  - mahesh
  
job 1:
     stage: Dev1
     script:
     condition: and(succeeded(),contains(variables['Build.SourceBranchName'], 'Dev1'))  

job 2:
     stage: master
     script:
     condition: and(succeeded(),contains(variables['Build.SourceBranchName'], 'master'))  


job 3:
     stage: mahesh
     script:
     condition: and(succeeded(),contains(variables['Build.SourceBranchName'], 'mahesh'))  