# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- mahesh

variables:
  imageName: latest:$(Build.SourceBranchName)-$(Build.BuildNumber)
  inputs:
      tags: 
       Build-$(Build.BuildNumber)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'




- script: |
    echo "SECRET_AUTH_AZURE_CLIENT_ID=$(SECRET_AUTH_AZURE_CLIENT_ID)" > .env
    echo "BUILD_SOURCEBRANCHNAME: $(BUILD_SOURCEBRANCHNAME)"
    echo "Build.BuildNumber: $(Build.BuildNumber)"
    echo "Build.SourceBranchName: $(Build.SourceBranchName)"
    echo "imageName: $(imageName)"
#    docker-compose build
  displayName: 'create .env file'


#- script: |
#    docker-compose run app npm i
#  displayName: 'Install node modules'
- task: PublishBuildArtifacts@1
  condition: and(succeeded(),contains(variables['Build.SourceBranchName'], 'master'))
  
    - script
     docker build -t agiletestpk.azurecr.io/$(imageName) .
     docker login -u $(dockerId) -p $(dockerPswd) $(dockerId).azurecr.io
     docker push $(dockerId).azurecr.io/$(imageName)
     displayName:'Build Docker Image'
     