pool:
  vmImage: 'ubuntu-latest'
    
  resources:         
  repositories:
  - repository: $(repo_name)   
    type: GitHub
    connection: myGitHubConnection
    source: $(repo_source)
    pr:
      branches:
        include:
        - develop
        - test
        - acceptance
        - master
        exclude:
      #  - releases/
    #  paths:
    #    include:
    #    - web/*         
    #    exclude:
    #    - web/README.md


        variables:
          imageName: agiletest:$(Build.SourceBranchName)-$(Build.BuildNumber)

        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
         
        - script: |
            echo "SECRET_AUTH_AZURE_CLIENT_ID=$(SECRET_AUTH_AZURE_CLIENT_ID)" > .env
            echo "Build.BuildNumber: $(Build.BuildNumber)"
            echo "Build.SourceBranchName: $(Build.SourceBranchName)"
            echo "imageName: $(imageName)"
          displayName: 'create .env file'

        - script: |
            docker build -t agiletest.azurecr.io/$(imageName)-$(Build.SourceBranchName) .
            docker login -u $(dockerId) -p $(dockerPswd) $(dockerId).azurecr.io
            docker push $(dockerId).azurecr.io/$(imageName)-$(Build.SourceBranchName)
          displayName: 'Build Docker Image'

